import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Harmonaig from '../components/Harmonaig'

import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>INSTRUO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>~INSTRUO*MODULAR~</h1>
        <div className={styles.moduleContainer}>
          <Harmonaig />
          <Harmonaig />
          <Harmonaig />
        </div>
        <Link href={'./texture'}>
          <button>GET STARTED</button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p>Made by Tim Dustow @ Dev Academy</p>
      </footer>
    </div>
  )
}
