import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Harmonaig from '../components/Harmonaig'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>INSTRUO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Harmonaig</h1>
        <div className={styles.moduleContainer}>
          <div className={styles.module}>
            <Harmonaig />
          </div>
          <div className={styles.card}>
            <h2>Harmonaig</h2>

            <div>
              <h3>Details</h3>
              <p>these are the details about harmonig</p>
              <h3>Price</h3>
              <p>$300</p>
              <Link href="/">
                <button>Add to Cart</button>
              </Link>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made by Tim Dustow @ Dev Academy</p>
      </footer>
    </div>
  )
}
